export const studioCopy = {
  en: {
    brand: 'Business Studio', draft: 'Invitation draft', saving: 'Saving…', saved: 'Saved', saveError: 'Not saved', language: 'العربية', back: 'Back to Business',
    areas: ['Campaign', 'Puzzle', 'Experience', 'Recipients', 'Delivery', 'Review'],
    areaNotes: ['Name & format', 'The creative', 'Invitation details', 'Personal versions', 'How it arrives', 'Final check'],
    eyebrow: ['Set the intention', 'Build the reveal', 'Shape the moment', 'One campaign, made personal', 'Choose the arrival', 'Ready when you are'],
    campaign: { title: 'What are you creating?', body: 'Start with the outcome. The studio will shape every other decision around it.', name: 'Campaign name', nameValue: 'The Atelier Opening', experience: 'Experience', invitation: 'Invitation', active: 'Available now', reveal: 'Reveal', challenge: 'Challenge', reward: 'Reward', coming: 'Coming next' },
    puzzle: { title: 'Make the invitation worth unlocking.', body: 'Choose the image, then tune the solve. The actual JIGZO remains the center of the experience.', image: 'Campaign image', upload: 'Choose image', mocked: 'Local preview only', difficulty: 'Difficulty', pieces: 'pieces', mystery: 'Mystery mode', mysteryBody: 'Keep the image hidden until the final piece lands.' },
    experience: { title: 'The invitation behind the puzzle.', body: 'Structured event details make the reveal clear, useful and personal.', invitationGroup: 'Invitation', invitationHint: 'Compose the moment they uncover.', detailsGroup: 'Event details', detailsHint: 'The essentials, kept quietly in place.', policyGroup: 'Guest policy', policyHint: 'Set the response rules for every recipient.', eventTitle: 'Event title', eventValue: 'An evening at The Atelier', date: 'Date & time', dateValue: '2026-10-24T19:30', timezone: 'Timezone', timezoneValue: 'Asia/Bahrain', location: 'Location', locationValue: 'The Atelier, Manama', deadline: 'RSVP deadline', deadlineValue: '2026-10-18', message: 'Invitation message', messageValue: 'Sara, we would love you to join us for an intimate evening of art, conversation and a little surprise.', rsvp: 'RSVP enabled', plusOne: 'Allow +1 by default' },
    recipients: { title: 'See one invitation become personal.', body: 'Select a recipient and the same campaign immediately becomes their version.', add: 'Add manually', upload: 'Upload CSV', template: 'Download template', cap: 'CSV · up to 2,000 recipients', selected: 'Previewing', edit: 'Edit', remove: 'Remove', plusOne: '+1 override', inherit: 'Campaign default', allow: 'Allow', block: 'Do not allow', valid: 'Ready', invalid: 'Check phone', duplicate: 'Duplicate', manual: 'Manual', imported: 'CSV import', empty: 'Select a valid recipient to preview their invitation.' },
    delivery: { title: 'Choose how the puzzle arrives.', body: 'Delivery is intentionally quiet in this phase. Nothing will be sent from this preview.', whatsapp: 'WhatsApp', whatsappBody: 'A direct puzzle link in a personal message.', email: 'Email', emailBody: 'A considered invitation with the puzzle as the focal action.', preview: 'Development preview', noSend: 'Sending is not connected yet.', launch: 'Launch Now only in V1' },
    review: { title: 'One last look, without the admin noise.', body: 'Everything the recipient will experience, distilled into a single campaign portrait.', campaign: 'Campaign', puzzle: 'Puzzle', event: 'Event', recipients: 'Recipients', delivery: 'Delivery', policy: 'RSVP policy', expiry: 'Deadline', ready: 'Frontend preview ready', launch: 'Launch unavailable in this phase', launchNow: 'Launch Now', validCount: '2 ready · 2 need attention', policyValue: 'Responses editable until deadline · +1 off' },
    preview: { label: 'Live recipient preview', solved: 'Puzzle solved', invitation: 'You’re invited', eventMeta: '24 OCT · 7:30 PM', going: 'Going', notGoing: 'Not going', guest: 'Bring a +1', personal: 'Personalized for', select: 'Select recipient', demo: 'Interactive frontend preview' },
    common: { on: 'On', off: 'Off', next: 'Next area', previous: 'Previous', complete: 'Complete', incomplete: 'In progress' }
  },
  ar: {
    brand: 'استوديو الأعمال', draft: 'مسودة دعوة', saving: 'جارٍ الحفظ…', saved: 'تم الحفظ', saveError: 'لم يتم الحفظ', language: 'English', back: 'العودة إلى الأعمال',
    areas: ['الحملة', 'الأحجية', 'التجربة', 'المستلمون', 'التوصيل', 'المراجعة'],
    areaNotes: ['الاسم والنوع', 'المشهد الإبداعي', 'تفاصيل الدعوة', 'نسخ شخصية', 'طريقة الوصول', 'النظرة الأخيرة'],
    eyebrow: ['حدّد الفكرة', 'ابنِ لحظة الكشف', 'صمّم اللحظة', 'حملة واحدة، بطابع شخصي', 'اختر طريقة الوصول', 'كل شيء في مكانه'],
    campaign: { title: 'ما التجربة التي تصنعها؟', body: 'ابدأ بالنتيجة التي تريدها، وسيبني الاستوديو بقية القرارات حولها.', name: 'اسم الحملة', nameValue: 'افتتاح الأتيليه', experience: 'نوع التجربة', invitation: 'دعوة', active: 'متاحة الآن', reveal: 'كشف', challenge: 'تحدٍّ', reward: 'مكافأة', coming: 'قريباً' },
    puzzle: { title: 'اجعل فتح الدعوة تجربة تستحق الحل.', body: 'اختر الصورة واضبط مستوى الأحجية. تظل تجربة JIGZO هي المشهد الأهم.', image: 'صورة الحملة', upload: 'اختر صورة', mocked: 'معاينة محلية فقط', difficulty: 'الصعوبة', pieces: 'قطعة', mystery: 'الوضع الغامض', mysteryBody: 'تبقى الصورة مخفية حتى تستقر القطعة الأخيرة.' },
    experience: { title: 'الدعوة التي تنتظر خلف الأحجية.', body: 'تفاصيل واضحة ومنظّمة تجعل لحظة الكشف مفيدة وشخصية.', invitationGroup: 'الدعوة', invitationHint: 'صُغ اللحظة التي سيكتشفونها.', detailsGroup: 'تفاصيل المناسبة', detailsHint: 'المعلومات الأساسية، بهدوء ووضوح.', policyGroup: 'سياسة الضيوف', policyHint: 'حدّد قواعد الرد لجميع المستلمين.', eventTitle: 'عنوان المناسبة', eventValue: 'أمسية في الأتيليه', date: 'التاريخ والوقت', dateValue: '2026-10-24T19:30', timezone: 'المنطقة الزمنية', timezoneValue: 'Asia/Bahrain', location: 'الموقع', locationValue: 'الأتيليه، المنامة', deadline: 'آخر موعد للرد', deadlineValue: '2026-10-18', message: 'نص الدعوة', messageValue: 'سارة، يسعدنا حضورك أمسية حميمة تجمع الفن والحديث ومفاجأة صغيرة.', rsvp: 'تفعيل تأكيد الحضور', plusOne: 'السماح بمرافق افتراضياً' },
    recipients: { title: 'شاهد الدعوة الواحدة تصبح شخصية.', body: 'اختر مستلماً، وستتحول الحملة نفسها فوراً إلى نسخته الخاصة.', add: 'إضافة يدوية', upload: 'رفع CSV', template: 'تنزيل النموذج', cap: 'CSV · حتى 2,000 مستلم', selected: 'تتم معاينته', edit: 'تعديل', remove: 'إزالة', plusOne: 'تخصيص المرافق', inherit: 'إعداد الحملة', allow: 'سماح', block: 'عدم السماح', valid: 'جاهز', invalid: 'راجع الهاتف', duplicate: 'مكرر', manual: 'يدوي', imported: 'استيراد CSV', empty: 'اختر مستلماً صالحاً لمعاينة دعوته.' },
    delivery: { title: 'اختر كيف تصل الأحجية.', body: 'التوصيل معروض بوضوح في هذه المرحلة، ولن تُرسل أي رسالة من هذه المعاينة.', whatsapp: 'واتساب', whatsappBody: 'رابط مباشر للأحجية ضمن رسالة شخصية.', email: 'البريد الإلكتروني', emailBody: 'دعوة أنيقة تكون الأحجية فيها هي الفعل الرئيسي.', preview: 'معاينة تطويرية', noSend: 'الإرسال غير متصل بعد.', launch: 'الإطلاق الفوري فقط في V1' },
    review: { title: 'نظرة أخيرة، بلا ضوضاء إدارية.', body: 'كل ما سيختبره المستلم، مختصر في صورة واحدة واضحة للحملة.', campaign: 'الحملة', puzzle: 'الأحجية', event: 'المناسبة', recipients: 'المستلمون', delivery: 'التوصيل', policy: 'سياسة الرد', expiry: 'الموعد النهائي', ready: 'معاينة الواجهة جاهزة', launch: 'الإطلاق غير متاح في هذه المرحلة', launchNow: 'إطلاق الآن', validCount: '2 جاهزان · 2 يحتاجان للمراجعة', policyValue: 'يمكن تعديل الرد حتى الموعد · المرافق غير مفعّل' },
    preview: { label: 'معاينة المستلم المباشرة', solved: 'تم حل الأحجية', invitation: 'أنت مدعو', eventMeta: '24 أكتوبر · 7:30 م', going: 'سأحضر', notGoing: 'لن أحضر', guest: 'سأحضر مع مرافق', personal: 'نسخة شخصية لـ', select: 'اختر مستلماً', demo: 'معاينة تفاعلية للواجهة' },
    common: { on: 'مفعّل', off: 'متوقف', next: 'المنطقة التالية', previous: 'السابق', complete: 'مكتمل', incomplete: 'قيد الإعداد' }
  }
};
