const Campaign=require('../models/Campaign');
const CampaignRecipient=require('../models/CampaignRecipient');
const RecipientSession=require('../models/RecipientSession');
const {randomToken,sha256}=require('../utils/businessSecurity');
const COOKIE='jigzo_invitation_session';
const SESSION_MS=7*24*60*60*1000;
function noStore(res){res.set({'Cache-Control':'private, no-store, max-age=0, must-revalidate','CDN-Cache-Control':'no-store','Vercel-CDN-Cache-Control':'no-store','Referrer-Policy':'no-referrer','Pragma':'no-cache'});}
function readCookie(header){for(const part of String(header||'').split(';')){const [key,...value]=part.trim().split('=');if(key===COOKIE)return value.join('=');}return '';}
function sessionCookie(token,expiresAt){const secure=process.env.NODE_ENV==='production'||Boolean(process.env.VERCEL);const seconds=Math.max(0,Math.floor((expiresAt-Date.now())/1000));return `${COOKIE}=${token}; Path=/api/public/invitations; HttpOnly; ${secure?'Secure; ':''}SameSite=Strict; Max-Age=${seconds}`;}
function campaignDeadline(campaign,now=new Date()){const limit=campaign.expiresAt?new Date(campaign.expiresAt):new Date(now.getTime()+SESSION_MS);return new Date(Math.min(limit.getTime(),now.getTime()+SESSION_MS));}
async function issueAccess(recipient){const raw=randomToken();const now=new Date();recipient.accessTokenHash=sha256(raw);recipient.accessTokenMode='random';recipient.accessIssuedAt=now;recipient.accessRevokedAt=null;await recipient.save();await RecipientSession.updateMany({recipientId:recipient._id,revokedAt:null},{$set:{revokedAt:now}});return raw;}
async function exchangeAccess(raw){const hash=sha256(raw);const recipient=await CampaignRecipient.findOne({accessTokenHash:hash,accessRevokedAt:null}).select('+accessTokenHash');if(!recipient)return null;const campaign=await Campaign.findOne({_id:recipient.campaignId,organizationId:recipient.organizationId,status:{$nin:['cancelled','completed']}});const now=new Date();if(!campaign||(campaign.expiresAt&&campaign.expiresAt<=now))return null;const token=randomToken();const expiresAt=campaignDeadline(campaign,now);await RecipientSession.create({tokenHash:sha256(token),organizationId:recipient.organizationId,campaignId:campaign._id,recipientId:recipient._id,accessTokenHash:hash,expiresAt,lastSeenAt:now});await CampaignRecipient.updateOne({_id:recipient._id,accessTokenHash:hash},{$set:{lastAccessAt:now}});return{token,expiresAt};}
async function resolveSession(req){const raw=readCookie(req.headers.cookie);if(!raw)return null;const now=new Date();const session=await RecipientSession.findOne({tokenHash:sha256(raw),revokedAt:null,expiresAt:{$gt:now}}).select('+accessTokenHash');if(!session)return null;const recipient=await CampaignRecipient.findOne({_id:session.recipientId,organizationId:session.organizationId,campaignId:session.campaignId,accessTokenHash:session.accessTokenHash,accessRevokedAt:null}).select('+accessTokenHash');const campaign=recipient&&await Campaign.findOne({_id:session.campaignId,organizationId:session.organizationId,status:{$nin:['cancelled','completed']}});if(!recipient||!campaign||(campaign.expiresAt&&campaign.expiresAt<=now))return null;RecipientSession.updateOne({_id:session._id},{$set:{lastSeenAt:now}}).catch(()=>{});return{session,recipient,campaign};}
function deliverySecret(){const value=String(process.env.BUSINESS_INVITATION_ACCESS_SECRET||'');if(value.length<32)throw Object.assign(new Error('BUSINESS_INVITATION_ACCESS_SECRET must be at least 32 characters.'),{code:'ACCESS_SECRET_MISSING',permanent:true});return value;}
function deriveDeliveryToken(recipientId,issuedAt){return require('crypto').createHmac('sha256',deliverySecret()).update(`delivery-access:v1:${recipientId}:${new Date(issuedAt).toISOString()}`).digest('base64url');}
async function issueDeliveryAccess(recipient){if(recipient.accessTokenMode==='derived'&&recipient.accessIssuedAt&&recipient.accessTokenHash){const existing=deriveDeliveryToken(recipient._id,recipient.accessIssuedAt);if(sha256(existing)===recipient.accessTokenHash&& !recipient.accessRevokedAt)return existing;}const now=new Date();const raw=deriveDeliveryToken(recipient._id,now);recipient.accessTokenHash=sha256(raw);recipient.accessTokenMode='derived';recipient.accessIssuedAt=now;recipient.accessRevokedAt=null;await recipient.save();await RecipientSession.updateMany({recipientId:recipient._id,revokedAt:null},{$set:{revokedAt:now}});return raw;}
module.exports={COOKIE,noStore,sessionCookie,issueAccess,issueDeliveryAccess,deriveDeliveryToken,exchangeAccess,resolveSession,campaignDeadline};
