const { v4: uuidv4 } = require('uuid');
const { normalizeRecipient, persistedRecipient, MAX_RECIPIENTS } = require('./recipientService');
const RecipientImport = require('../models/RecipientImport'); const CampaignRecipient = require('../models/CampaignRecipient');
const COLUMNS = ['name','contact_method','contact','plus_one_override'];
const EXAMPLE_ROWS = [
  ['Sara','whatsapp','+973XXXXXXXX',''],
  ['Omar','email','omar@example.com','ON'],
  ['Noor','whatsapp','+973XXXXXXXX','OFF']
];
function assertCsvContentType(value){if(String(value||'').split(';')[0].trim().toLowerCase()!=='text/csv')throw Object.assign(new Error('Only text/csv uploads are supported.'),{statusCode:415,code:'WRONG_FILE_TYPE'});}
function parseCsv(text) { const rows=[]; let row=[],cell='',quoted=false; const source=String(text||'').replace(/^\uFEFF/,''); for(let i=0;i<source.length;i++){const ch=source[i];if(quoted){if(ch==='"'&&source[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch;}else if(ch==='"'&&cell==='')quoted=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;} if(quoted) throw Object.assign(new Error('Malformed CSV: unclosed quoted field.'),{statusCode:400,code:'MALFORMED_CSV'}); if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);} return rows; }
const sanitizeFilename = value => String(value||'recipients.csv').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,120) || 'recipients.csv';
async function validateImport({ text, filename, organizationId, campaign, Models = {} }) { const Import=Models.RecipientImport||RecipientImport, Recipient=Models.CampaignRecipient||CampaignRecipient; const rows=parseCsv(text); if(rows.length<2) throw Object.assign(new Error('CSV must contain a header and recipient rows.'),{statusCode:400}); const headers=rows[0].map(x=>String(x).trim().toLowerCase()); if(new Set(headers).size!==headers.length) throw Object.assign(new Error('Duplicate CSV columns are not allowed.'),{statusCode:400,code:'DUPLICATE_COLUMNS'}); if(headers.length!==COLUMNS.length||headers.some((h,i)=>h!==COLUMNS[i])) throw Object.assign(new Error('CSV columns do not match template version 1.'),{statusCode:400,code:'UNSUPPORTED_COLUMNS'}); const dataRows=rows.slice(1).filter(row=>row.some(cell=>String(cell).trim())); if(dataRows.length>MAX_RECIPIENTS) throw Object.assign(new Error(`CSV exceeds ${MAX_RECIPIENTS} recipients.`),{statusCode:413,code:'RECIPIENT_LIMIT'});
  if(dataRows.some(row=>row.length!==headers.length))throw Object.assign(new Error('Malformed CSV: inconsistent column count.'),{statusCode:400,code:'MALFORMED_CSV'});
  const existing=await Recipient.find({organizationId,campaignId:campaign._id}).select('+contactHash').lean(); const contacts=new Set(existing.map(x=>x.contactHash)), refs=new Set(existing.map(x=>x.externalRef).filter(Boolean)); const seenContacts=new Set(),seenRefs=new Set(),stagedRows=[],errorSummary=[]; let validCount=0,invalidCount=0,duplicateCount=0;
  dataRows.forEach((values,index)=>{const input=Object.fromEntries(headers.map((h,i)=>[h,values[i]??'']));const normalized=normalizeRecipient(input,campaign.invitation?.language||'en');let classification='ready';const errors=[...normalized.errors];if(!errors.length&&(contacts.has(normalized.contactHash)||seenContacts.has(normalized.contactHash)||normalized.externalRef&&(refs.has(normalized.externalRef)||seenRefs.has(normalized.externalRef)))){classification='duplicate';errors.push('duplicate_recipient');duplicateCount++;}else if(errors.length){classification='needs_fixing';invalidCount++;}else{validCount++;seenContacts.add(normalized.contactHash);if(normalized.externalRef)seenRefs.add(normalized.externalRef);stagedRows.push({...persistedRecipient(normalized,{organizationId,campaignId:campaign._id,source:'import',rowNumber:index+2}),recipientId:undefined,organizationId:undefined,campaignId:undefined,source:undefined});}errorSummary.push({rowNumber:index+2,displayName:normalized.displayName,maskedContact:normalized.maskedContact,classification,validationErrors:errors});});
  return Import.create({importId:uuidv4(),organizationId,campaignId:campaign._id,originalFilename:sanitizeFilename(filename),rowCount:dataRows.length,validCount,invalidCount,duplicateCount,status:'validated',errorSummary,stagedRows,expiresAt:new Date(Date.now()+24*60*60*1000)});
}
async function commitImport(record,{Models={}}={}){const Import=Models.RecipientImport||RecipientImport,Recipient=Models.CampaignRecipient||CampaignRecipient;if(record.status==='completed')return record;const claimed=await Import.findOneAndUpdate({_id:record._id,status:'validated'},{$set:{status:'committing'}},{new:true}).select('+stagedRows');if(!claimed){return Import.findById(record._id);}let committed=0,commitErrors=[];for(let i=0;i<claimed.stagedRows.length;i+=200){const docs=claimed.stagedRows.slice(i,i+200).map(row=>({recipientId:uuidv4(),organizationId:claimed.organizationId,campaignId:claimed.campaignId,source:'import',importId:claimed._id,...row.toObject?.()||row}));try{const result=await Recipient.insertMany(docs,{ordered:false});committed+=result.length;}catch(error){committed+=error.insertedDocs?.length||0;commitErrors.push('Some rows conflicted during commit.');}}return Import.findOneAndUpdate({_id:claimed._id},{$set:{status:'completed',committedCount:committed,committedAt:new Date(),commitErrors,stagedRows:[]}},{new:true}).select('-stagedRows');}
module.exports={COLUMNS,EXAMPLE_ROWS,assertCsvContentType,parseCsv,sanitizeFilename,validateImport,commitImport};
