const express=require('express'); const Campaign=require('../models/Campaign'); const CampaignRecipient=require('../models/CampaignRecipient'); const RecipientImport=require('../models/RecipientImport');
const {requireBusinessAuth,requireBusinessCsrf}=require('../middleware/businessAuth'); const {tenantCampaignFilter}=require('../services/campaignService'); const {MAX_RECIPIENTS,normalizeRecipient,persistedRecipient,serializeRecipient,assertNoDuplicate}=require('../services/recipientService'); const {COLUMNS,EXAMPLE_ROWS,assertCsvContentType,validateImport,commitImport}=require('../services/recipientImportService');
const router=express.Router(); router.use(requireBusinessAuth);
async function campaignFor(req,res){const campaign=await Campaign.findOne(tenantCampaignFilter(req.business.organizationId,req.params.campaignId));if(!campaign){res.status(404).json({error:'Campaign not found.'});return null;}campaign.invitation.language=req.business.organization.defaultLanguage;return campaign;}
router.get('/:campaignId/recipients/template',async(req,res)=>{if(!await campaignFor(req,res))return;res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="jigzo-recipient-template-v1.csv"');return res.send('\uFEFF'+[COLUMNS,...EXAMPLE_ROWS].map(row=>row.join(',')).join('\r\n')+'\r\n');});
router.get('/:campaignId/recipients',async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;const rows=await CampaignRecipient.find({organizationId:req.business.organizationId,campaignId:campaign._id,source:{$ne:'test'}}).select('+contactEncrypted').sort({createdAt:1});return res.json({success:true,count:rows.length,recipients:rows.map(row=>serializeRecipient(row,true))});}catch(e){next(e);}});
router.get('/:campaignId/recipients/:recipientId',async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;const row=await CampaignRecipient.findOne({organizationId:req.business.organizationId,campaignId:campaign._id,recipientId:req.params.recipientId}).select('+contactEncrypted');if(!row)return res.status(404).json({error:'Recipient not found.'});return res.json({success:true,recipient:serializeRecipient(row,true)});}catch(e){next(e);}});
router.post('/:campaignId/recipients',requireBusinessCsrf,async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;if(await CampaignRecipient.countDocuments({organizationId:req.business.organizationId,campaignId:campaign._id,source:{$ne:'test'}})>=MAX_RECIPIENTS)return res.status(409).json({error:'Campaign recipient limit reached.',code:'RECIPIENT_LIMIT'});const normalized=normalizeRecipient(req.body,campaign.invitation?.language||'en');if(normalized.errors.length)return res.status(422).json({error:'Recipient needs fixing.',errors:normalized.errors});await assertNoDuplicate({organizationId:req.business.organizationId,campaignId:campaign._id,contactHash:normalized.contactHash,externalRef:normalized.externalRef});const row=await CampaignRecipient.create(persistedRecipient(normalized,{organizationId:req.business.organizationId,campaignId:campaign._id,source:'manual'}));return res.status(201).json({success:true,recipient:serializeRecipient(row)});}catch(e){if(e.code===11000)return res.status(409).json({error:'Duplicate recipient.',code:'DUPLICATE_RECIPIENT'});next(e);}});
router.patch('/:campaignId/recipients/:recipientId',requireBusinessCsrf,async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;const current=await CampaignRecipient.findOne({organizationId:req.business.organizationId,campaignId:campaign._id,recipientId:req.params.recipientId}).select('+contactEncrypted');if(!current)return res.status(404).json({error:'Recipient not found.'});const normalized=normalizeRecipient(req.body,campaign.invitation?.language||'en');if(normalized.errors.length)return res.status(422).json({error:'Recipient needs fixing.',errors:normalized.errors});await assertNoDuplicate({organizationId:req.business.organizationId,campaignId:campaign._id,contactHash:normalized.contactHash,externalRef:normalized.externalRef,excludeRecipientId:current.recipientId});Object.assign(current,persistedRecipient(normalized,{organizationId:req.business.organizationId,campaignId:campaign._id,source:current.source,importId:current.importId,rowNumber:current.importRowNumber}),{recipientId:current.recipientId});await current.save();return res.json({success:true,recipient:serializeRecipient(current)});}catch(e){if(e.code===11000)return res.status(409).json({error:'Duplicate recipient.',code:'DUPLICATE_RECIPIENT'});next(e);}});
router.delete('/:campaignId/recipients/:recipientId',requireBusinessCsrf,async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;const result=await CampaignRecipient.deleteOne({organizationId:req.business.organizationId,campaignId:campaign._id,recipientId:req.params.recipientId});if(!result.deletedCount)return res.status(404).json({error:'Recipient not found.'});return res.json({success:true});}catch(e){next(e);}});
router.post('/:campaignId/imports',requireBusinessCsrf,(req,res,next)=>{try{assertCsvContentType(req.get('content-type'));return express.text({type:'text/csv',limit:'2mb'})(req,res,next);}catch(error){return res.status(error.statusCode).json({error:error.message,code:error.code});}},async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;const existing=await CampaignRecipient.countDocuments({organizationId:req.business.organizationId,campaignId:campaign._id,source:{$ne:'test'}});const record=await validateImport({text:req.body,filename:req.get('x-jigzo-filename'),organizationId:req.business.organizationId,campaign});if(existing+record.validCount>MAX_RECIPIENTS){await RecipientImport.deleteOne({_id:record._id});return res.status(409).json({error:'Import would exceed campaign recipient limit.',code:'RECIPIENT_LIMIT'});}return res.status(201).json({success:true,import:record,editableRows:record.editableRows||[]});}catch(e){next(e);}});
router.get('/:campaignId/imports/:importId',async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;const record=await RecipientImport.findOne({organizationId:req.business.organizationId,campaignId:campaign._id,importId:req.params.importId});if(!record)return res.status(404).json({error:'Import not found.'});return res.json({success:true,import:record});}catch(e){next(e);}});
router.post('/:campaignId/imports/:importId/commit',requireBusinessCsrf,async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;const record=await RecipientImport.findOne({organizationId:req.business.organizationId,campaignId:campaign._id,importId:req.params.importId});if(!record)return res.status(404).json({error:'Import not found.'});const result=await commitImport(record);return res.json({success:true,import:result});}catch(e){next(e);}});
module.exports=router;
