const express=require('express');const Campaign=require('../models/Campaign');const CampaignRecipient=require('../models/CampaignRecipient');const Puzzle=require('../models/Puzzle');const storage=require('../services/storageService');const {requireBusinessAuth,requireBusinessCsrf}=require('../middleware/businessAuth');const {tenantCampaignFilter}=require('../services/campaignService');const {issueAccess}=require('../services/invitationAccessService');const {persistCampaignPuzzle}=require('../services/businessPuzzleService');const {getFrontendOrigin}=require('../utils/runtimeConfig');const {stripUnsafe,normalizeRecipient,persistedRecipient}=require('../services/recipientService');
const router=express.Router();router.use(requireBusinessAuth);
async function campaignFor(req,res){const campaign=await Campaign.findOne(tenantCampaignFilter(req.business.organizationId,req.params.campaignId));if(!campaign){res.status(404).json({error:'Campaign not found.'});return null;}return campaign;}
router.post('/:campaignId/puzzle',requireBusinessCsrf,express.raw({type:['image/jpeg','image/png','image/webp'],limit:'3mb'}),async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;const puzzle=await persistCampaignPuzzle(campaign,{mime:req.get('content-type'),buffer:req.body});return res.status(201).json({success:true,puzzle:{persisted:true,pieceCount:puzzle.pieceCount,mysteryMode:campaign.puzzle.mysteryMode}});}catch(e){next(e);}});
router.get('/:campaignId/puzzle/image',async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;const puzzle=await Puzzle.findOne({_id:campaign.puzzle?.puzzleId,scope:'business',organizationId:req.business.organizationId,businessCampaignId:campaign._id});if(!puzzle?.imageStorageId)return res.status(404).json({error:'Image not found.'});res.set({'Cache-Control':'private, no-store','Referrer-Policy':'no-referrer'});res.type(puzzle.imageMimeType||'image/jpeg');storage.getImageStream(puzzle.imageStorageId).on('error',next).pipe(res);}catch(e){next(e);}});
router.post('/:campaignId/recipients/:recipientId/access-link',requireBusinessCsrf,async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;if(!campaign.puzzle?.puzzleId)return res.status(409).json({error:'Persist the campaign puzzle before issuing a link.',code:'PUZZLE_REQUIRED'});const recipient=await CampaignRecipient.findOne({organizationId:req.business.organizationId,campaignId:campaign._id,recipientId:req.params.recipientId}).select('+accessTokenHash');if(!recipient)return res.status(404).json({error:'Recipient not found.'});const raw=await issueAccess(recipient);return res.status(201).json({success:true,link:`${getFrontendOrigin()}/i#t=${raw}`,issuedAt:recipient.accessIssuedAt});}catch(e){next(e);}});
// "Preview as guest": the sender opens the REAL /i journey (envelope -> shared
// PuzzlePlayer -> reveal -> RSVP) via a real, secure access token minted by the exact
// same issueAccess() the real launch flow uses — no new session/security code path.
// Isolation is via a single per-campaign synthetic 'test' CampaignRecipient, reused (not
// duplicated) across repeat clicks and reset to a fresh unsolved/pending state every time
// so the sender can re-run the whole journey after tweaking settings. This row is
// deliberately excluded everywhere real recipients are counted, launched to, or
// aggregated into results — see source:{$ne:'test'} in businessRecipients.js,
// campaignLaunchService.js, campaignService.js and the /results query below.
router.post('/:campaignId/preview-recipient',requireBusinessCsrf,async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;if(!campaign.puzzle?.puzzleId)return res.status(409).json({error:'Persist the campaign puzzle before previewing.',code:'PUZZLE_REQUIRED'});const language=req.business.organization.defaultLanguage||'en';const rawName=stripUnsafe(req.body?.name);const displayName=rawName||(language==='ar'?'ضيف المعاينة':'Preview guest');const normalized=normalizeRecipient({name:displayName,contact_method:'email',contact:`preview-${campaign.campaignId}@preview.internal.jigzo`},language);if(normalized.errors.length)return res.status(422).json({error:'Could not build a preview recipient.'});let recipient=await CampaignRecipient.findOne({organizationId:req.business.organizationId,campaignId:campaign._id,source:'test'}).select('+accessTokenHash');if(recipient){recipient.displayName=normalized.displayName;recipient.language=normalized.language;recipient.firstOpenedAt=null;recipient.firstSolvedAt=null;recipient.completionSeconds=null;recipient.rsvpStatus='pending';recipient.guestCount=0;recipient.respondedAt=null;await recipient.save();}else{try{recipient=await CampaignRecipient.create(persistedRecipient(normalized,{organizationId:req.business.organizationId,campaignId:campaign._id,source:'test'}));}catch(e){if(e.code!==11000)throw e;recipient=await CampaignRecipient.findOne({organizationId:req.business.organizationId,campaignId:campaign._id,source:'test'}).select('+accessTokenHash');if(!recipient)throw e;}}const raw=await issueAccess(recipient);return res.status(201).json({success:true,link:`${getFrontendOrigin()}/i#t=${raw}`});}catch(e){next(e);}});
router.get('/:campaignId/results',async(req,res,next)=>{try{const campaign=await campaignFor(req,res);if(!campaign)return;const recipients=await CampaignRecipient.find({organizationId:req.business.organizationId,campaignId:campaign._id,source:{$ne:'test'}}).sort({createdAt:1});const rows=recipients.map(r=>({recipientId:r.recipientId,displayName:r.displayName,maskedContact:r.maskedContact,opened:Boolean(r.firstOpenedAt),solved:Boolean(r.firstSolvedAt),rsvpStatus:r.rsvpStatus,guestCount:r.guestCount,responseTimestamp:r.respondedAt,completionSeconds:r.completionSeconds}));return res.json({success:true,summary:{totalRecipients:rows.length,unopened:rows.filter(r=>!r.opened).length,opened:rows.filter(r=>r.opened).length,solved:rows.filter(r=>r.solved).length,rsvpPending:rows.filter(r=>r.rsvpStatus==='pending').length,going:rows.filter(r=>r.rsvpStatus==='going').length,notGoing:rows.filter(r=>r.rsvpStatus==='not_going').length,totalConfirmedGuests:rows.reduce((n,r)=>n+(r.rsvpStatus==='going'?r.guestCount:0),0)},recipients:rows});}catch(e){next(e);}});
module.exports=router;
