const express=require('express');const {rateLimit}=require('express-rate-limit');const CampaignRecipient=require('../models/CampaignRecipient');const Puzzle=require('../models/Puzzle');const InvitationResponseEvent=require('../models/InvitationResponseEvent');const storage=require('../services/storageService');const {sha256}=require('../utils/businessSecurity');const {noStore,sessionCookie,exchangeAccess,resolveSession}=require('../services/invitationAccessService');
const {effectivePlusOne,assertResponseOpen,normalizeResponse}=require('../services/invitationPolicy');const router=express.Router();router.use((req,res,next)=>{noStore(res);next();});
router.post('/exchange',rateLimit({windowMs:60*1000,limit:10,standardHeaders:'draft-7',legacyHeaders:false}),async(req,res,next)=>{try{const token=String(req.body?.token||'');if(!/^[A-Za-z0-9_-]{40,100}$/.test(token))return res.status(401).json({error:'Invalid invitation access.'});const result=await exchangeAccess(token);if(!result)return res.status(401).json({error:'Invalid invitation access.'});res.setHeader('Set-Cookie',sessionCookie(result.token,result.expiresAt));return res.json({success:true});}catch(e){next(e);}});
async function session(req,res){const value=await resolveSession(req);if(!value)res.status(401).json({error:'Invitation session required.'});return value;}
function reveal(campaign,recipient){return{eventTitle:campaign.invitation.eventTitle,eventDateTime:campaign.invitation.eventDateTime,timezone:campaign.invitation.timezone,location:campaign.invitation.location,rsvpDeadline:campaign.invitation.rsvpDeadline,message:recipient.invitationMessageOverride||campaign.invitation.message,rsvpEnabled:campaign.invitation.rsvpEnabled,allowPlusOne:effectivePlusOne(campaign,recipient)};}
router.get('/session',async(req,res,next)=>{try{const value=await session(req,res);if(!value)return;const {campaign,recipient}=value;return res.json({success:true,recipient:{displayName:recipient.displayName,language:recipient.language,opened:Boolean(recipient.firstOpenedAt),solved:Boolean(recipient.firstSolvedAt),rsvpStatus:recipient.rsvpStatus,guestCount:recipient.guestCount},campaign:{name:campaign.name,expired:Boolean(campaign.expiresAt&&campaign.expiresAt<=new Date())},invitation:recipient.firstSolvedAt?reveal(campaign,recipient):null});}catch(e){next(e);}});
router.get('/puzzle',async(req,res,next)=>{try{const value=await session(req,res);if(!value)return;const puzzle=await Puzzle.findOne({_id:value.campaign.puzzle?.puzzleId,scope:'business',organizationId:value.campaign.organizationId,businessCampaignId:value.campaign._id});if(!puzzle)return res.status(404).json({error:'Puzzle not ready.'});return res.json({success:true,puzzle:{pieceCount:puzzle.pieceCount,mysteryMode:value.campaign.puzzle.mysteryMode,imageUrl:value.campaign.puzzle.mysteryMode?null:'/api/public/invitations/image'}});}catch(e){next(e);}});
router.get('/image',async(req,res,next)=>{try{const value=await session(req,res);if(!value)return;if(value.campaign.puzzle.mysteryMode&&!value.recipient.firstSolvedAt)return res.status(403).json({error:'Reveal image is withheld until solved.'});const puzzle=await Puzzle.findOne({_id:value.campaign.puzzle?.puzzleId,scope:'business',organizationId:value.campaign.organizationId,businessCampaignId:value.campaign._id});if(!puzzle?.imageStorageId)return res.status(404).json({error:'Image not found.'});res.type(puzzle.imageMimeType||'image/jpeg');storage.getImageStream(puzzle.imageStorageId).on('error',next).pipe(res);}catch(e){next(e);}});
router.post('/open',async(req,res,next)=>{try{const value=await session(req,res);if(!value)return;const now=new Date();await CampaignRecipient.updateOne({_id:value.recipient._id,firstOpenedAt:null},{$set:{firstOpenedAt:now}});return res.json({success:true});}catch(e){next(e);}});
router.post('/solve',async(req,res,next)=>{try{const value=await session(req,res);if(!value)return;const now=new Date();const duration=Math.max(0,Math.min(86400,Number.parseInt(req.body?.durationSeconds,10)||0));await CampaignRecipient.updateOne({_id:value.recipient._id,firstOpenedAt:null},{$set:{firstOpenedAt:now}});await CampaignRecipient.updateOne({_id:value.recipient._id,firstSolvedAt:null},{$set:{firstSolvedAt:now,completionSeconds:duration}});const recipient=await CampaignRecipient.findById(value.recipient._id);return res.json({success:true,invitation:reveal(value.campaign,recipient),recipient:{displayName:recipient.displayName,rsvpStatus:recipient.rsvpStatus,guestCount:recipient.guestCount}});}catch(e){next(e);}});
router.put('/response',async(req,res,next)=>{try{const value=await session(req,res);if(!value)return;const {campaign,recipient}=value;if(!recipient.firstSolvedAt)return res.status(403).json({error:'Solve the puzzle before responding.',code:'SOLVE_REQUIRED'});const now=new Date();try{assertResponseOpen(campaign,now);}catch(e){return res.status(409).json({error:e.message,code:e.code});}const key=String(req.get('idempotency-key')||'');if(!key||key.length>200)return res.status(400).json({error:'A valid Idempotency-Key is required.'});const keyHash=sha256(key);const prior=await InvitationResponseEvent.findOne({recipientId:recipient._id,idempotencyKeyHash:keyHash});if(prior)return res.json({success:true,idempotent:true,response:{status:prior.toStatus,guestCount:prior.guestCount,respondedAt:prior.respondedAt}});let normalized;try{normalized=normalizeResponse(req.body,campaign,recipient);}catch(e){return res.status(422).json({error:e.message,code:e.code});}const event=await InvitationResponseEvent.create({organizationId:recipient.organizationId,campaignId:campaign._id,recipientId:recipient._id,idempotencyKeyHash:keyHash,fromStatus:recipient.rsvpStatus,toStatus:normalized.status,guestCount:normalized.guestCount,respondedAt:now});await CampaignRecipient.updateOne({_id:recipient._id},{$set:{rsvpStatus:normalized.status,guestCount:normalized.guestCount,respondedAt:now}});return res.json({success:true,response:{status:event.toStatus,guestCount:event.guestCount,respondedAt:event.respondedAt}});}catch(e){if(e.code===11000){const prior=await InvitationResponseEvent.findOne({recipientId:req.invitationRecipientId,idempotencyKeyHash:req.invitationKeyHash});if(prior)return res.json({success:true,idempotent:true,response:{status:prior.toStatus,guestCount:prior.guestCount,respondedAt:prior.respondedAt}});}next(e);}});
module.exports=router;
