export const COUNTRIES = [
  { code: "BH", flag: "🇧🇭", dial: "+973" },
  { code: "SA", flag: "🇸🇦", dial: "+966" },
  { code: "AE", flag: "🇦🇪", dial: "+971" },
  { code: "KW", flag: "🇰🇼", dial: "+965" },
  { code: "QA", flag: "🇶🇦", dial: "+974" },
  { code: "OM", flag: "🇴🇲", dial: "+968" },
  { code: "JO", flag: "🇯🇴", dial: "+962" },
  { code: "EG", flag: "🇪🇬", dial: "+20" },
  { code: "GB", flag: "🇬🇧", dial: "+44" },
  { code: "US", flag: "🇺🇸", dial: "+1" },
  { code: "IN", flag: "🇮🇳", dial: "+91" },
  { code: "PK", flag: "🇵🇰", dial: "+92" },
  { code: "TR", flag: "🇹🇷", dial: "+90" },
  { code: "FR", flag: "🇫🇷", dial: "+33" },
  { code: "DE", flag: "🇩🇪", dial: "+49" },
];
