export const PIECE_OPTIONS = [
  { count: 6,  cols: 2, rows: 3, label: "Extra Easy",  pieces: "6 pieces",  copy: "Perfect for a quick surprise." },
  { count: 15, cols: 3, rows: 5, label: "Easy",        pieces: "15 pieces", copy: "A light challenge with a quick reveal." },
  { count: 18, cols: 3, rows: 6, label: "Classic",     pieces: "18 pieces", copy: "Just the right balance of fun and anticipation.", recommended: true },
  { count: 28, cols: 4, rows: 7, label: "Challenging", pieces: "28 pieces", copy: "For those who enjoy making the moment last." },
];

export const OCCASIONS = [
  { id: "love", label: "Love" },
  { id: "birthday", label: "Birthday" },
  { id: "anniversary", label: "Anniversary" },
  { id: "congrats", label: "Congratulations" },
  { id: "sorry", label: "I'm Sorry" },
  { id: "missyou", label: "Miss You" },
  { id: "getwell", label: "Get Well Soon" },
  { id: "thankyou", label: "Thank You" },
  { id: "newbaby", label: "New Baby" },
  { id: "justbecause", label: "Just Because" },
];

export const TONES = [
  { id: "romantic", label: "Romantic" },
  { id: "funny", label: "Funny" },
  { id: "deep", label: "Deep" },
  { id: "short", label: "Short" },
  { id: "poetic", label: "Poetic" },
  { id: "family", label: "Family" },
  { id: "friendship", label: "Friendship" },
  { id: "playful", label: "Playful" },
];

export const MESSAGES = {
  love: {
    romantic: "Every love story is different. Mine simply became my favorite the day you walked into it.",
    funny: "I was going to write something incredibly romantic... then I remembered you already know I'm obsessed with you.",
    deep: "Loving you never felt like a decision. It felt like finally recognizing where I belonged.",
    short: "You still feel like my favorite hello.",
    poetic: "If my heart had a language, every sentence would somehow end with your name.",
    family: "Home stopped being a place the day it became you.",
    friendship: "Every great friendship deserves someone brave enough to admit... I think mine became love.",
    playful: "Congratulations... you're officially stuck with me.",
  },
  birthday: {
    romantic: "Another birthday, another reminder of how lucky I am that you exist.",
    funny: "You're not getting older... you're just becoming a classic.",
    deep: "I hope this year brings you moments you'll remember long after you've forgotten today's gifts.",
    short: "Today belongs to you. Enjoy every second.",
    poetic: "May this year leave beautiful fingerprints on your soul.",
    family: "Thank you for making our family brighter simply by being you.",
    friendship: "Life became more fun the day we became friends.",
    playful: "Eat the cake. Blame tomorrow.",
  },
  anniversary: {
    romantic: "Every year with you feels less like time passing and more like memories collecting.",
    funny: "We survived another year of my terrible jokes. That's real commitment.",
    deep: "Love isn't measured by years together. It's measured by choosing each other every day.",
    short: "Still my favorite person.",
    poetic: "Some promises grow more beautiful every sunrise.",
    family: "Thank you for building a life our family gets to call home.",
    friendship: "My favorite relationship began with my favorite friendship.",
    playful: "I'd still swipe right.",
  },
  congrats: {
    romantic: "Watching you succeed is one of my greatest joys.",
    funny: "Finally! Now everyone else knows how amazing you are.",
    deep: "Success is simply the world catching up with your effort.",
    short: "You earned every bit of this.",
    poetic: "Dreams bloom quietly before the world notices the flowers.",
    family: "You've made us all incredibly proud.",
    friendship: "Watching you win feels like winning a little myself.",
    playful: "Okay... now don't forget us when you're famous.",
  },
  sorry: {
    romantic: "If love means anything, it means trying to become better after hurting the one you love.",
    funny: "I'm officially applying for the position of \"Person Who Learns From Their Mistakes.\"",
    deep: "I can't rewrite yesterday, but I can choose who I become tomorrow.",
    short: "I'm truly sorry.",
    poetic: "Even broken moments deserve gentle healing.",
    family: "Family deserves patience. I'm sorry I forgot that.",
    friendship: "I'd rather repair this friendship than win any argument.",
    playful: "Peace offering accepted? (Please say yes.)",
  },
  missyou: {
    romantic: "Distance changes where we are, never where my heart stays.",
    funny: "Please come back. I'm running out of people willing to laugh at my jokes.",
    deep: "Some people leave an absence louder than any noise.",
    short: "I miss you.",
    poetic: "Even the quiet reminds me of you.",
    family: "Home feels smaller without you here.",
    friendship: "Missing a friend is just another way of appreciating them.",
    playful: "Hurry back. Life is getting boring.",
  },
  getwell: {
    romantic: "I'll be here through every good day and every difficult one.",
    funny: "Your only job right now is to rest. I'll allow it.",
    deep: "Healing takes courage, even on the quiet days.",
    short: "One day at a time.",
    poetic: "Storms eventually become stories.",
    family: "We're all waiting to see your smile again.",
    friendship: "Rest today. Adventures can wait.",
    playful: "Doctor's orders: Accept unlimited hugs.",
  },
  thankyou: {
    romantic: "Thank you for loving me in ways words will never fully explain.",
    funny: "I'd say I owe you one... but we're way past keeping score.",
    deep: "Kindness leaves marks we rarely get to see. Yours changed me.",
    short: "Thank you. Truly.",
    poetic: "Gratitude is love remembered.",
    family: "Thank you for everything you've quietly done for us.",
    friendship: "Every good friend deserves to hear they're appreciated.",
    playful: "You're officially my favorite human today.",
  },
  newbaby: {
    romantic: "Our greatest adventure has just begun.",
    funny: "Sleep is cancelled. Love has officially arrived.",
    deep: "Tiny hands. Endless possibilities.",
    short: "Welcome, little one.",
    poetic: "A new heartbeat has rewritten the rhythm of this family.",
    family: "Our family just became even more beautiful.",
    friendship: "Your little miracle is already so loved.",
    playful: "The smallest boss has officially arrived.",
  },
  justbecause: {
    romantic: "I didn't need a reason to think about you. I just did.",
    funny: "No occasion. No excuse. Just me being awesome enough to send you this.",
    deep: "The best reminders are the ones no one expected.",
    short: "You matter.",
    poetic: "Some thoughts deserve to travel farther than silence.",
    family: "Just a reminder that you're loved more than you know.",
    friendship: "Friends don't always need a reason to make each other smile.",
    playful: "Surprise! This puzzle contains 100% appreciation.",
  },
};

export function suggestedMessage(occ, tone) {
  return (occ && tone && MESSAGES[occ] && MESSAGES[occ][tone]) || "";
}
