import React,{useCallback,useEffect,useRef,useState}from'react';import PuzzlePlayer from'../components/PuzzlePlayer';import{invitationExchange}from'../services/invitationBootstrap';import{invitationApi}from'../services/invitationApi';import'./invitation-recipient.css';
const COPY={en:{loading:'Opening your JIGZO…',invalid:'This invitation link is invalid or has expired.',for:'Made personally for',solved:'Puzzle solved',invited:"You’re invited",going:'Going',plus:'Going +1',no:'Not going',confirmed:'Your response is saved.',change:'Change response',closed:'RSVP is closed.'},ar:{loading:'جارٍ فتح JIGZO الخاص بك…',invalid:'رابط الدعوة غير صالح أو انتهت صلاحيته.',for:'صُممت خصيصاً لـ',solved:'تم حل الأحجية',invited:'أنت مدعو',going:'سأحضر',plus:'سأحضر +1',no:'لن أحضر',confirmed:'تم حفظ ردك.',change:'تغيير الرد',closed:'انتهى وقت الرد.'}};
export default function InvitationRecipientPage(){const[phase,setPhase]=useState('loading');const[session,setSession]=useState(null);const[puzzle,setPuzzle]=useState(null);const[data,setData]=useState(null);const[invitation,setInvitation]=useState(null);const[response,setResponse]=useState(null);const[error,setError]=useState('');const start=useRef(Date.now());const lang=session?.recipient?.language||'en';const c=COPY[lang];
useEffect(()=>{let active=true;(async()=>{try{await invitationExchange;const s=await invitationApi.session();if(!active)return;setSession(s);document.documentElement.lang=s.recipient.language;document.documentElement.dir=s.recipient.language==='ar'?'rtl':'ltr';if(s.recipient.solved){setInvitation(s.invitation);setResponse(s.recipient.rsvpStatus==='pending'?null:{status:s.recipient.rsvpStatus,guestCount:s.recipient.guestCount});setPhase('invitation');return;}const p=await invitationApi.puzzle();await invitationApi.open();if(!active)return;setPuzzle(p.puzzle);setData({pieceCount:p.puzzle.pieceCount,cropImageUrl:p.puzzle.imageUrl,recipient:{name:s.recipient.displayName},message:'',experienceLanguage:s.recipient.language});start.current=Date.now();setPhase('puzzle');}catch(e){if(active){setError(e.message);setPhase('error');}}})();return()=>{active=false;};},[]);
const solved=useCallback(async seconds=>{const result=await invitationApi.solve(seconds);setInvitation(result.invitation);setSession(value=>({...value,recipient:{...value.recipient,solved:true}}));setPhase('invitation');return{success:true,message:'unlocked'};},[]);
const respond=async(status,guestCount)=>{try{const result=await invitationApi.respond({status,guestCount},crypto.randomUUID());setResponse(result.response);setPhase('confirmed');}catch(e){setError(e.response?.data?.error||c.closed);}};
if(phase==='loading')return <main className="jzi-state"><span className="jzi-mark">JIGZO</span><p>{c.loading}</p></main>;if(phase==='error')return <main className="jzi-state"><span className="jzi-mark">JIGZO</span><p>{c.invalid}</p></main>;
if(phase==='puzzle')return <main className="jzi-page" dir={lang==='ar'?'rtl':'ltr'}><header><span className="jzi-mark">JIGZO</span><small>{c.for} {session.recipient.displayName}</small></header><PuzzlePlayer data={data} setData={setData} publicId="business-invitation" rIndex={0} startTimeRef={start} onSolved={solved}/></main>;
return <main className="jzi-page jzi-reveal" dir={lang==='ar'?'rtl':'ltr'}><header><span className="jzi-mark">JIGZO</span><small>{c.solved}</small></header><article className="jzi-invitation"><p className="jzi-kicker">{c.invited}</p><h1>{invitation.eventTitle}</h1><dl><div><dt>{new Date(invitation.eventDateTime).toLocaleString(lang==='ar'?'ar-BH':'en-GB',{dateStyle:'long',timeStyle:'short',timeZone:invitation.timezone})}</dt><dd>{invitation.timezone}</dd></div><div><dt>{invitation.location}</dt></div></dl><p className="jzi-message">{invitation.message}</p>{invitation.rsvpDeadline&&<small>{new Date(invitation.rsvpDeadline).toLocaleString(lang==='ar'?'ar-BH':'en-GB')}</small>}{phase==='confirmed'?<div className="jzi-confirm"><strong>{c.confirmed}</strong><button onClick={()=>setPhase('invitation')}>{c.change}</button></div>:invitation.rsvpEnabled&&<div className="jzi-actions"><button onClick={()=>respond('going',1)}>{c.going}</button>{invitation.allowPlusOne&&<button onClick={()=>respond('going',2)}>{c.plus}</button>}<button className="secondary" onClick={()=>respond('not_going',0)}>{c.no}</button></div>}{error&&<p className="jzi-error">{error}</p>}</article></main>}
